
[commands.slackowwalllog]
description="Describes how to send a SlackowWallLog"
message="""
To send a log from SlackowWall:
- Make sure your game is open
- Open SlackowWall Settings
- Look under the "Credits & Help" tab
- Press the button/link towards the bottom of the page.

Your log file contains specs, SlackowWall settings, and NinjabrainBot settings, \
as well as the mods you use, and any errors that may have occurred.
"""

[commands.fn_f3]
description="Describes how to remove the requirement for pressing fn with F3"
message="""
In order to `F3 + C`, you cannot press `fn + F3 + C`, because `fn + C` is bound \
to opening the control center. You can override this in a number of ways:
- Turning on the macOS setting under `Keyboard > Keyboard Shortcuts... > Function Keys`
- Using [Karabiner Elements](<https://karabiner-elements.pqrs.org/>), which is trickier \
to setup but allows for more advanced rebinding options
- Using [Fluor](<https://fluorapp.net/>), which simply changes the function row between \
function keys and action keys, depending on the app you're in. (Easier to setup)
If you have a touchbar instead of physical keys, \
follow the instructions under `/fn_f3_touchbar` instead
"""

[commands.fn_f3_touchbar]
description="Describes how to remove the requirement for pressing fn with F3 with a touchbar"
message="""
If you have a touchbar, you can do the following to show the function row while you're in Minecraft:

- Open the "Terminal" app
- Copy, paste and run this command (`⌘ + V, return/enter`)
```sh
defaults write com.apple.touchbar.agent PresentationModePerApp -dict-add net.java.openjdk.cmd functionKeys \
net.java.openjdk.java functionKeys com.azul.zulu.java functionKeys
sudo killall TouchBarServer NowPlayingTouchUI ControlStrip
```
you may be prompted for your password
"""

[commands.blankprojector]
description="Describes how to fix a blank eye projector in SlackowWall"
message="""
A blank eye projector is usually caused by using retiNO mod, not using the BoundlessWindow mod, \
or not having Screen Recording permissions.

Ensure you've done the following:
- Disabled/not using retiNO mod
- Are using the [BoundlessWindow mod](<https://github.com/Slackow/BoundlessWindow/releases/latest>)
- Have the "Remove Titlebar" option on in BoundlessWindow settings
- Have Screen Recording permissions enabled for SlackowWall
- If you previously set your tall height to `16384`, remove this override and allow it to default to avoid a crash.
  (You should still use `16384` in Ninjabrain Bot, because your Minecraft resolution is different from your window size)

For more details and alternatives to retiNO mod, read this \
[document](<https://docs.google.com/document/d/1gD_ZZYFCEOJxImyfpUxLHGn702moP9I69-46fhWe9QM/edit?usp=sharing>)

If you still have a blank eye projector, send a SlackowWall log file and tag Slackow.
instructions for that can be found under `/slackowwalllog`
"""

[commands.sensitivity_scaling]
description="Describes what sensitivity scaling is"
message="""
BoatEye requires using specific sensitivities, and the sensitivities that work really well are \
all small, (the most common of `0.02291165` is ~4%). Sensitivity Scaling allows you to translate your \
"locked" mouse speed without affecting your regular mouse speed. So in practice you keep your minecraft sensitivity the same \
(`0.02291165`) and change the slider in SlackowWall instead. (You can also type in an exact value by clicking the text)

Note that this affects your mouse whenever it's locked, that's why there's convenient ways to toggle it, such as \
the toolbar icon, and the global hotkey if you need to quickly toggle it but are mid match.

It's also used to slow down your mouse when measuring eyes.
BoatEye is only impacted by the in-game sensitivity value, so other stuff like scaling, or \
mouse dpi/system sensitivity have no impact on measurements.

If you press the red x next to "BoatEye Sensitivity", it will automatically change the sensitivity for you. \
(Shows up with your game open)
"""

[commands.tall_mode_crash]
description="Describes the likely cause of a crash when entering tall mode"
message="""
If you manually set your tall mode height to 16384, you might experience a crash when resizing. \
This is due to the difference between window size and minecraft resolution.

On some screens the minecraft resolution is double the window size, and on others it matches it (HiDPI vs LoDPI). \
So the game is resizing to a minecraft resolution height of 32768 (double 16384), which crashes.

If you remove the tall mode height setting, that should resolve the crash (SlackowWall figures out what you need). \
NinjabrainBot should still be set to use 16384, because it only cares about your minecraft resolution. Read the document for more info[.](https://docs.google.com/document/d/1gD_ZZYFCEOJxImyfpUxLHGn702moP9I69-46fhWe9QM/edit?tab=t.0#heading=h.q72fbwoqngrh)
"""

[commands.macman]
description="Describes the Mac Man bot"
message="""
Yo, I'm Mac Man, created by Slackow.
Most of my commands just relay information about common issues or troubleshooting guides on macOS, \
related to speedrunning.

I was made in Swift and am either hosted on a Mac Mini or an Oracle server running Linux.
(mostly to stick with the Mac theme, Python or TypeScript is more suitable for a bot this simple)
Here's my [source code](<https://github.com/Slackow/MacMan>)
Have a Mac wonderful day!
"""

[commands.boateye]
description="Describes how to setup SlackowWall"
message="""
# To setup BoatEye on macOS
- Download and install [SlackowWall](<https://github.com/Slackow/SlackowWall>), and [NinjabrainBot](<https://github.com/Ninjabrain1/Ninjabrain-Bot>)
- Grant SlackowWall the necessary permissions (screen recording & accessibility)
- Grant NinjabrainBot the necessary permissions (accessibility)
- If not on macOS Sequoia (15) make sure you are *not* using the retiNO mod, and that you do have the [Boundless Window mod](<https://github.com/Slackow/BoundlessWindow/releases/latest>)
- With BoundlessWindow, Minecraft will go onto your "Main display" so you may have to change that in display settings if you use an external display.
- Make sure you have "Video Settings... > Fullscreen" off
# In SlackowWall:
- Enter settings, and go under Window Resizing to configure your hotkey for tall mode, and other modes you may use.
- Under Utility Settings, enable Eye Projector, and Sensitivity Scaling.
- Set the Simulated Sensitivity slider to the sensitivity you use in game
- Make sure BoatEye sensitivity is set to `0.02291165`
- With your game open, press the red x that appears next to BoatEye sensitivity
This should set your in-game sensitivity to the BoatEye sensitivity (~4%).
You should not change your in-game sensitivity. (change the slider instead)
Sensitivity Scaling makes your in-game sens feel like your normal sens, it only works *while SlackowWall is open*. \
You can use the toolbar icon or hotkey to toggle it on/off easier, and by default it will slow down your mouse in tall mode.

run `/boateye_ninbot` for instructions on setting up NinjabrainBot
run `/boateye_obs` for instructions on changing OBS
run `/eyemeasuring` for instructions on measuring
"""

[commands.boateye_ninbot]
description="Describes how to setup Ninjabrain Bot for BoatEye"
message="""
# In NinjabrainBot:
- Enter Settings, go under Hotkeys (it may appear blank the first time)
- Configure the hotkeys for "Reset" and adjusting your angle +/-0.01, be mindful that the first one is +
- Go under "Optional features > Boat measurement"
- Set "Sensitivity 1.13+" to `0.02291165`
- Set "Default boat mode" to `Green boat`
- Set Standard deviation for boat throws to `0.0007`
- Go under "Angle adjustment"
- Set "Adjustment display type" to `Number of adjustments`
- Set "Pixel adjustment type" to `Tall resolution`
- Set "Resolution height" to `16384`
- Restart NinjabrainBot
- Press your "Reset" hotkey (your boat should turn green)

run `/boateye` for instructions on setting up SlackowWall if you haven't already
run `/boateye_obs` for instructions on changing OBS
run `/eyemeasuring` for instructions on measuring
You should be setup. (You don't need to calibrate NinjabrainBot if you use BoatEye)
"""

[commands.boateye_obs]
description="Describes how to setup your Minecraft source in OBS"
message="""
For your game to show up properly in OBS:
- Create/reuse a macOS screen capture, and set it to `Window Capture`
- Select your game as the window (you can type "[j" in the dropdown to find it immediately)
- Press "Ok", then press `⌘ + E` on the source
- Set "Bounding Box Type" to `Scale to inner bounds`
- Set "Alignment in Bounding Box" to `Center`
- Set "Bounding Box Size" to your output resolution, e.g. `1920 x 1080`
- Press "Close"
- Optionally add an image source for NinjabrainBot, the path should appear in NinjabrainBot \
under the "OBS overlay" section. You can use the `⌘ + ⇧ + G` shortcut in finder to make typing in the path easier
You should see that in tall mode, your game will not be cut off.
You will have to reselect the window every time you restart your game
"""

[commands.eyemeasuring]
description="Describes how to measure your eye"
message="""
For when you have green boat and a sensitivity of `0.02291165`:
make sure you have followed all steps in `/boateye`
- If and only if you entered a boat during the run, and pressed a and d while in it: make sure you have entered and left a boat before measuring. \
(You do not have to record the angle, simply enter and leave it without pressing a/d, at any point before measuring.)
- Throw your eye, making sure your server/client positions are not [desynced](<https://www.youtube.com/watch?v=uBqAeZMlEFQ>)
- Line your mouse up to the eye, and enter 30 FOV.
- Press your tall mode hotkey.
- Move your mouse even closer to the boundary between the center of the eye[,]\
(https://raw.githubusercontent.com/Slackow/SlackowWall/main/Info/images/eyeProjector.png) \
and pause buffer if necessary (pausing while holding f3)
- Once you see the intersection between the middle and left pixels on your eye projector, do not move your mouse, and press `f3 + c`.
- Then enter the input as it reads on the eye projector, right side is +, left side is -.
- The result should then (hopefully) be accurate
"""

[commands.f3_c]
description="Describes why f3+c may not be working"
message="""
If f3 + c isn't working, make sure:
- NinjabrainBot has accessibility permissions granted
- You have the setting under "Advanced > Alternative Clipboard Reader" off
If you are not seeing "Location copied to clipboard" when pressing `f3 + c`, and you're pressing \
`fn + f3 + c`, consult `/fn_f3`
"""

[commands.command_q]
description="Describes how to unbind command + q for Minecraft"
message="""
You can unbind `⌘ + Q` for Minecraft specifically, so that you can use it to drop a full stack of items[.](https://cdn.discordapp.com/attachments/1115090281453322402/1430669408920932452/image.png?ex=6932a5f7&is=69315477&hm=dd152ef42617d60b0aab17b8da4d7e596d8bef554e43ff2d4c9928cec1b21c68&)
The setting is under "Keyboard > Keyboard Shortcuts... > App Shortcuts", where you can add a shortcut called \
"Quit java" (Case Sensitive) and set it to whatever you like (e.g. `^ + ⌥ + Q`)
Older versions may require specialized names (<1.13)
"""

[commands.update_mods]
description="Describes how to update your mods"
message="""
You can update your mods through [SlackowWall](<https://github.com/Slackow/SlackowWall>) or [ModCheck](<https://github.com/tildejustin/modcheck>)
If you have SlackowWall, just make sure you are in utility mode, and click the arrow in the top right of your instance.
Then click the "View Mods" option, and in that menu, press the button the update your mods. (This will close your game)
"""

[commands.clear_worlds]
description="Describes how to clear your worlds"
message="""
In SlackowWall's Utility mode, there's an option called "Clear Worlds" underneath the arrow in the top right corner. \
This will delete all but the 30 most recent worlds created with names like "New World, Random Speedrun etc." \
Personal worlds and maps should be safe as long as their **Folders** do not have these names.
"""

[commands.multimc_to_prism]
description="Explains the significance of Prism vs MultiMC for macOS"
message="""
If you are using a Mac made after 2020, with an M series chip (e.g. M1, M2, etc) \
then you should be using PrismLauncher instead of MultiMC.
This is because MultiMC only supports Intel Chips, while PrismLauncher supports ARM (apple chips) and Intel. \
In practice, this means if you are using MultiMC, you are running an Intel Version of Java through a translation layer that makes it work on ARM. \
This drastically reduces performance.

Prism is directly based on MultiMC and has all of its features (and more). In fact, migrating to Prism is usually as simple as copying or moving your instances from one folder to another[.](https://prismlauncher.org/wiki/getting-started/migrating-multimc/)
"""

[commands.slackowwall]
description="Gets the download link to SlackowWall"
message="""
Download SlackowWall from [GitHub](https://github.com/Slackow/SlackowWall/releases/latest)

If you have [Homebrew](https://brew.sh) you can run this:
```bash
brew install slackow/apps/slackowwall
```
"""

[commands.boundless_window]
description="Links to boundless window mod"
message="""
Download BoundlessWindow from [GitHub](<https://github.com/Slackow/BoundlessWindow/releases/latest>), \
[ModCheck](<https://github.com/tildejustin/modcheck/releases/latest>), or \
[mods.tildejustin.dev](<https://mods.tildejustin.dev>)

BoundlessWindow allows you to resize your minecraft window larger than your monitor height, \
which it is normally limited to.
"""
